# Generated by Django 5.0.6 on 2025-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
