# Generated by Django 5.0.6 on 2024-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0003_alter_products_code_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='made_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
