# Generated by Django 5.0.6 on 2024-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0004_customer_made_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='provided',
            field=models.BooleanField(default=False),
        ),
    ]
