# Generated by Django 5.0.6 on 2024-09-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0005_customerproduct_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='made_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
